### ISSUE TITLE
Relation between id class from yolo and pt 

### ISSUE THREAD

**Issue by 0xPinole** [0xPinole/vision-ros#18]

**Comment by cBarredez** [comment]
I am on it

**Comment by cBarredez** [comment]
``colors:
- [126, 42, 81]
- [138, 134, 213]
- [172, 12, 140]
- [102, 214, 136]
- [188, 98, 41]
- [201, 126, 231]
- [122, 48, 41]
- [104, 162, 37]
- [23, 161, 176]
- [45, 125, 159]
- [112, 88, 46]
- [75, 70, 221]
- [124, 223, 155]
- [1, 223, 20]
- [224, 227, 120]
- [153, 87, 0]
- [255, 184, 41]
- [96, 53, 177]
- [113, 216, 44]
- [96, 246, 166]
- [214, 160, 138]
- [46, 133, 120]
- [168, 239, 93]
- [218, 193, 129]
- [219, 67, 74]
- [236, 65, 185]
names: [KIRKLAN TOWEL ROLL, JUBILE BIG ROLL, BATH/TISSUE/KIRKLAND, OVEN BAGS, AXION/LIMON425G,
  NAPKINS KIRTLAND, OVEN BAGS TASTIER, ZIPLOC 40  UND, MELODY/NAPKINS/180CT, REYNOLDS/WRAP
    30SQ, EASY-OFF 24 OZ, PINALEN/28FL, AJAX/BLEACH 14OZ, COMET, LYSOL SPRAY 19 OZ,
  WINDEX ORIGINAL 23OZ, CLORALEX/BLECH/950ML, SALVO LIMON 500ML, GLAD/15BAGS/39gal/FO,
  DAWN 7.5 OZ, ARIEL D.P./2KG, LYSOL 80WIPES, FABULOSO RED 1L, CLORALEN/650ML, FABULOSO/GREEN,
  FABULOSO PRIMAVERAL]
nc: 26
train: /content/drive/MyDrive/proyecto final/dataset_test3/images/train
val: /content/drive/MyDrive/proyecto final/dataset_test3/images/val

**Comment by cBarredez** [comment]
here is the YAML
[data_config.zip](https://github.com/0xPinole/vision-ros/files/15171964/data_config.zip)

**Comment by 0xPinole** [comment]
it's perfect, ty
